package com.rain.demo.entity;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.article_id
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    private Integer article_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.title
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.user_id
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.category_id
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    private Integer category_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.post_time
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    private Date post_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.likes
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    private Integer likes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.comment_account
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    private Integer comment_account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.content
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.article_id
     *
     * @return the value of articles.article_id
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public Integer getArticle_id() {
        return article_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.article_id
     *
     * @param article_id the value for articles.article_id
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public void setArticle_id(Integer article_id) {
        this.article_id = article_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.title
     *
     * @return the value of articles.title
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.title
     *
     * @param title the value for articles.title
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.user_id
     *
     * @return the value of articles.user_id
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.user_id
     *
     * @param user_id the value for articles.user_id
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.category_id
     *
     * @return the value of articles.category_id
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public Integer getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.category_id
     *
     * @param category_id the value for articles.category_id
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public void setCategory_id(Integer category_id) {
        this.category_id = category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.post_time
     *
     * @return the value of articles.post_time
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public Date getPost_time() {
        return post_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.post_time
     *
     * @param post_time the value for articles.post_time
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public void setPost_time(Date post_time) {
        this.post_time = post_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.likes
     *
     * @return the value of articles.likes
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.likes
     *
     * @param likes the value for articles.likes
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.comment_account
     *
     * @return the value of articles.comment_account
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public Integer getComment_account() {
        return comment_account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.comment_account
     *
     * @param comment_account the value for articles.comment_account
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public void setComment_account(Integer comment_account) {
        this.comment_account = comment_account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.content
     *
     * @return the value of articles.content
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.content
     *
     * @param content the value for articles.content
     *
     * @mbggenerated Mon Feb 04 10:59:50 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}