package com.rain.demo.entity;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_id
     *
     * @mbggenerated Mon Feb 04 11:00:12 CST 2019
     */
    private Integer category_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbggenerated Mon Feb 04 11:00:12 CST 2019
     */
    private String category_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_id
     *
     * @return the value of category.category_id
     *
     * @mbggenerated Mon Feb 04 11:00:12 CST 2019
     */
    public Integer getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_id
     *
     * @param category_id the value for category.category_id
     *
     * @mbggenerated Mon Feb 04 11:00:12 CST 2019
     */
    public void setCategory_id(Integer category_id) {
        this.category_id = category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbggenerated Mon Feb 04 11:00:12 CST 2019
     */
    public String getCategory_name() {
        return category_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param category_name the value for category.category_name
     *
     * @mbggenerated Mon Feb 04 11:00:12 CST 2019
     */
    public void setCategory_name(String category_name) {
        this.category_name = category_name == null ? null : category_name.trim();
    }
}