package com.rain.demo.entity;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    private Integer comment_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.article_id
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    private Integer article_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_time
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    private Date comment_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.likes
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    private String likes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public Integer getComment_id() {
        return comment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param comment_id the value for comment.comment_id
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public void setComment_id(Integer comment_id) {
        this.comment_id = comment_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param user_id the value for comment.user_id
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.article_id
     *
     * @return the value of comment.article_id
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public Integer getArticle_id() {
        return article_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.article_id
     *
     * @param article_id the value for comment.article_id
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public void setArticle_id(Integer article_id) {
        this.article_id = article_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_time
     *
     * @return the value of comment.comment_time
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public Date getComment_time() {
        return comment_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_time
     *
     * @param comment_time the value for comment.comment_time
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public void setComment_time(Date comment_time) {
        this.comment_time = comment_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.likes
     *
     * @return the value of comment.likes
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public String getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.likes
     *
     * @param likes the value for comment.likes
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public void setLikes(String likes) {
        this.likes = likes == null ? null : likes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Mon Feb 04 11:00:28 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}