package com.rain.demo.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.role_id
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    private Integer role_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.phone_number
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    private String phone_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param user_id the value for users.user_id
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.role_id
     *
     * @return the value of users.role_id
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public Integer getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.role_id
     *
     * @param role_id the value for users.role_id
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public void setRole_id(Integer role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.phone_number
     *
     * @return the value of users.phone_number
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public String getPhone_number() {
        return phone_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.phone_number
     *
     * @param phone_number the value for users.phone_number
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public void setPhone_number(String phone_number) {
        this.phone_number = phone_number == null ? null : phone_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Mon Feb 04 10:59:18 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public User(Integer user_id, String name, String password, Integer role_id, String phone_number, String email) {
        this.user_id = user_id;
        this.name = name;
        this.password = password;
        this.role_id = role_id;
        this.phone_number = phone_number;
        this.email = email;
    }
}